<?php

return [
    'pages' => [
        'home' => [
            'name' => 'Home',
            'view' => 'pages.home',
            'defaults' => [
                'meta' => [
                    'meta_title' => 'Sahayog Foundation — Empowering Communities Across India',
                    'meta_description' => 'Sahayog Foundation works with underserved communities in India to provide education, healthcare, and sustainable livelihoods. Join us in making a difference.',
                    'meta_keywords' => 'NGO, charity, donate, education, health, community, Sahayog Foundation',
                    'og_title' => 'Sahayog Foundation — Empowering Communities Across India',
                    'og_description' => 'Join Sahayog Foundation in building a better India through education, health, and opportunity.',
                    'og_image' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200',
                ],
                'content' => [
                    'hero_eyebrow' => 'Changing lives since 2010',
                    'hero_headline_line_1' => 'Every Child Deserves',
                    'hero_headline_highlight' => 'Brighter',
                    'hero_headline_line_2' => 'Tomorrow',
                    'hero_subtitle' => 'We partner with communities to break the cycle of poverty through education, healthcare, and sustainable livelihoods — one family at a time.',
                    'hero_primary_cta' => 'Donate Today',
                    'hero_secondary_cta' => 'Our Story',
                    'stats' => [
                        ['number' => 42000, 'suffix' => '+', 'label' => 'Lives Impacted'],
                        ['number' => 180, 'suffix' => '+', 'label' => 'Villages Reached'],
                        ['number' => 95, 'suffix' => '%', 'label' => 'Program Success Rate'],
                        ['number' => 12, 'suffix' => '', 'label' => 'Years of Service'],
                    ],
                    'about_eyebrow' => 'Who We Are',
                    'about_title_line_1' => 'Rooted in Community,',
                    'about_title_line_2' => 'Driven by Purpose',
                    'about_body_1' => 'Sahayog Foundation was born from a simple belief: that every human being deserves dignity, opportunity, and the tools to shape their own future. Since 2010, we have worked alongside communities — not for them — to create lasting change.',
                    'about_body_2' => 'Our approach is holistic. We address the interconnected roots of poverty by focusing on education, health, environment, and economic opportunity simultaneously.',
                    'about_values' => ['Community-First', 'Transparent', 'Sustainable', 'Accountable'],
                    'about_cta' => 'Meet Our Team',
                    'programs_eyebrow' => 'What We Do',
                    'programs_title_line_1' => 'Programs That Create',
                    'programs_title_line_2' => 'Lasting Change',
                    'programs_subtitle' => 'We run integrated programs across five key areas, designed to address root causes rather than symptoms.',
                    'programs' => [
                        [
                            'id' => 'education',
                            'title' => 'Education',
                            'desc' => 'Bridging the learning gap through scholarships, digital literacy, and quality coaching for underprivileged students.',
                            'stat' => '12,000+ students enrolled',
                            'color' => 'orange',
                        ],
                        [
                            'id' => 'health',
                            'title' => 'Healthcare',
                            'desc' => 'Mobile health camps, maternal care, and preventive medicine reaching the most remote communities.',
                            'stat' => '8,500+ patients treated',
                            'color' => 'yellow',
                        ],
                        [
                            'id' => 'livelihood',
                            'title' => 'Livelihoods',
                            'desc' => 'Skill training, microfinance linkages, and self-help group formation empowering families toward financial independence.',
                            'stat' => '3,200+ families supported',
                            'color' => 'orange',
                        ],
                        [
                            'id' => 'environment',
                            'title' => 'Environment',
                            'desc' => 'Watershed management, tree plantation, and clean energy adoption for a sustainable future.',
                            'stat' => '50,000+ trees planted',
                            'color' => 'yellow',
                        ],
                        [
                            'id' => 'women',
                            'title' => 'Women Empowerment',
                            'desc' => 'Leadership training, legal literacy, and entrepreneurship support for women to lead change in their communities.',
                            'stat' => '5,800+ women empowered',
                            'color' => 'orange',
                        ],
                        [
                            'id' => 'digital',
                            'title' => 'Digital Inclusion',
                            'desc' => 'Bringing internet access, e-governance training, and digital skills to rural communities across Maharashtra.',
                            'stat' => '200+ digital centers',
                            'color' => 'yellow',
                        ],
                    ],
                    'testimonials_eyebrow' => 'Real Stories',
                    'testimonials_title' => 'Voices from the Community',
                    'testimonials' => [
                        [
                            'quote' => "Sahayog's scholarship changed everything. I was about to drop out in Class 9. Today I am a computer science student at Pune University. I want to come back and give back.",
                            'name' => 'Priya Kamble',
                            'role' => 'Scholarship Beneficiary',
                            'location' => 'Solapur, Maharashtra',
                            'img' => 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&auto=format&fit=crop&q=80',
                        ],
                        [
                            'quote' => 'Our self-help group received training and a small loan through the foundation. We now run a successful tailoring unit with 11 women. We are independent.',
                            'name' => 'Meena Jadhav',
                            'role' => 'SHG Leader',
                            'location' => 'Nashik, Maharashtra',
                            'img' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
                        ],
                        [
                            'quote' => "The mobile health camp visited our village for the first time. My son's eye disease was caught early. Without this, he could have lost his sight. Thank you.",
                            'name' => 'Ramesh Patil',
                            'role' => 'Community Member',
                            'location' => 'Osmanabad, Maharashtra',
                            'img' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
                        ],
                    ],
                    'cta_eyebrow' => 'Make a Difference',
                    'cta_title_line_1' => 'Together, We Can Do',
                    'cta_title_line_2' => 'So Much More',
                    'cta_subtitle' => 'Your contribution — however small — ripples through generations. Help us reach the next village, the next child, the next family.',
                    'cta_primary_cta' => 'Donate Now',
                    'cta_secondary_cta' => 'Volunteer With Us',
                ],
                'media' => [
                    'hero_background' => [
                        'label' => 'Hero Background Image',
                        'path' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1600&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Children learning together in a bright classroom',
                    ],
                    'about_main_image' => [
                        'label' => 'About Section Main Image',
                        'path' => 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=700&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Volunteer teaching children in rural school',
                    ],
                    'about_secondary_image' => [
                        'label' => 'About Section Secondary Image',
                        'path' => 'https://images.unsplash.com/photo-1571210862729-78a52d3779a2?w=400&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Community health camp in progress',
                    ],
                    'cta_background' => [
                        'label' => 'Final CTA Background Image',
                        'path' => 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=1600&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Community volunteers standing together',
                    ],
                ],
            ],
            'editor' => [
                'quick_fields' => [
                    'Hero' => [
                        ['key' => 'hero_eyebrow', 'label' => 'Hero Eyebrow', 'type' => 'text'],
                        ['key' => 'hero_headline_line_1', 'label' => 'Hero Headline Line 1', 'type' => 'text'],
                        ['key' => 'hero_headline_highlight', 'label' => 'Hero Highlight Word', 'type' => 'text'],
                        ['key' => 'hero_headline_line_2', 'label' => 'Hero Headline Line 2', 'type' => 'text'],
                        ['key' => 'hero_subtitle', 'label' => 'Hero Subtitle', 'type' => 'textarea'],
                    ],
                    'About Preview' => [
                        ['key' => 'about_eyebrow', 'label' => 'About Eyebrow', 'type' => 'text'],
                        ['key' => 'about_title_line_1', 'label' => 'About Title Line 1', 'type' => 'text'],
                        ['key' => 'about_title_line_2', 'label' => 'About Title Line 2', 'type' => 'text'],
                        ['key' => 'about_body_1', 'label' => 'About Paragraph 1', 'type' => 'textarea'],
                        ['key' => 'about_body_2', 'label' => 'About Paragraph 2', 'type' => 'textarea'],
                        ['key' => 'about_cta', 'label' => 'About CTA Text', 'type' => 'text'],
                    ],
                    'Advanced JSON' => [
                        ['key' => 'stats', 'label' => 'Stats (JSON)', 'type' => 'json'],
                        ['key' => 'programs', 'label' => 'Programs List (JSON)', 'type' => 'json'],
                        ['key' => 'testimonials', 'label' => 'Testimonials (JSON)', 'type' => 'json'],
                    ],
                ],
                'media_keys' => ['hero_background', 'about_main_image', 'about_secondary_image', 'cta_background'],
            ],
        ],

        'about' => [
            'name' => 'About',
            'view' => 'pages.about',
            'defaults' => [
                'meta' => [
                    'meta_title' => 'About Us — Sahayog Foundation',
                    'meta_description' => "Learn about Sahayog Foundation's mission, values, history, and the dedicated team driving change in communities across India.",
                    'meta_keywords' => 'about sahayog foundation, ngo mission, ngo team, social impact india',
                    'og_title' => 'About Sahayog Foundation — Our Story & Team',
                    'og_description' => 'Meet the passionate people behind Sahayog Foundation and learn why we do what we do.',
                    'og_image' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=1200',
                ],
                'content' => [
                    'hero_title' => 'Our Story',
                    'hero_subtitle' => 'Built on trust, driven by compassion.',
                    'mission_title' => 'Our Mission',
                    'mission_text' => 'To work in solidarity with marginalized communities to enable them to lead dignified, healthy, and productive lives — through participatory development, rights-based advocacy, and sustainable programs.',
                    'vision_title' => 'Our Vision',
                    'vision_text' => 'An India where every community has equitable access to education, health, and opportunity — and the agency to shape its own future free from poverty and discrimination.',
                    'values_eyebrow' => 'What Guides Us',
                    'values_title' => 'Our Core Values',
                    'values' => [
                        ['icon' => '🤝', 'title' => 'Community Ownership', 'desc' => 'Communities are not beneficiaries — they are partners and leaders in every initiative we undertake.'],
                        ['icon' => '🔍', 'title' => 'Transparency', 'desc' => 'We publish annual reports, audited accounts, and impact data publicly. Your trust is our foundation.'],
                        ['icon' => '♻️', 'title' => 'Sustainability', 'desc' => 'We design programs to become community-owned and self-sustaining, not dependent on external support forever.'],
                        ['icon' => '⚖️', 'title' => 'Equity & Inclusion', 'desc' => 'We prioritize the most marginalized: women, Dalits, Adivasis, and persons with disabilities.'],
                        ['icon' => '📊', 'title' => 'Evidence-Based', 'desc' => 'Every program is tracked, measured, and iterated based on real field data and community feedback.'],
                        ['icon' => '💛', 'title' => 'Compassion', 'desc' => 'Behind every number is a human being. We lead with empathy in every interaction and decision.'],
                    ],
                    'journey_eyebrow' => 'Since 2010',
                    'journey_title' => 'Our Journey',
                    'milestones' => [
                        ['year' => '2010', 'title' => 'Founded', 'desc' => 'Sahayog Foundation registered as a public charitable trust in Pune with a small team of 5.'],
                        ['year' => '2012', 'title' => 'Education Program Launched', 'desc' => 'First scholarship program reaches 200 students across 3 districts of Maharashtra.'],
                        ['year' => '2015', 'title' => 'Healthcare Initiative', 'desc' => 'Mobile health van program launched, conducting over 1,200 camps in the first year.'],
                        ['year' => '2017', 'title' => 'National Award', 'desc' => 'Recognized by the Ministry of Social Justice for outstanding community development work.'],
                        ['year' => '2020', 'title' => 'COVID Relief', 'desc' => 'Provided food rations, hygiene kits, and mental health support to 25,000 families during the pandemic.'],
                        ['year' => '2023', 'title' => '40,000+ Lives Impacted', 'desc' => 'Crossed a major milestone with presence in 180+ villages and 14 active programs running simultaneously.'],
                    ],
                    'team_eyebrow' => 'The People Behind the Work',
                    'team_title' => 'Meet Our Team',
                    'team_subtitle' => 'A diverse group of changemakers united by a single purpose.',
                    'team' => [
                        [
                            'name' => 'Dr. Anjali Sharma',
                            'role' => 'Founder & Executive Director',
                            'bio' => 'Former IAS officer with 20 years in grassroots development. Passionate about rights-based approaches to poverty alleviation.',
                            'img' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
                        ],
                        [
                            'name' => 'Vikram Deshpande',
                            'role' => 'Director of Programs',
                            'bio' => 'Social entrepreneur with expertise in livelihood programs, microfinance, and community mobilization across five states.',
                            'img' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
                        ],
                        [
                            'name' => 'Sunita Rao',
                            'role' => 'Head of Education',
                            'bio' => 'Former schoolteacher turned education activist. Has built learning programs reaching over 12,000 students across Maharashtra.',
                            'img' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&auto=format&fit=crop&q=80',
                        ],
                        [
                            'name' => 'Dr. Rajan Nair',
                            'role' => 'Head of Healthcare',
                            'bio' => 'Public health specialist with WHO experience. Designs mobile healthcare models that work in the most resource-scarce settings.',
                            'img' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
                        ],
                        [
                            'name' => 'Kavitha Menon',
                            'role' => 'Communications Manager',
                            'bio' => 'Storyteller and journalist who ensures every voice from the field is heard. Manages donor relations and advocacy campaigns.',
                            'img' => 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&auto=format&fit=crop&q=80',
                        ],
                        [
                            'name' => 'Arun Pawar',
                            'role' => 'Finance & Compliance',
                            'bio' => 'Chartered accountant ensuring full financial transparency, FCRA compliance, and responsible stewardship of donor funds.',
                            'img' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
                        ],
                    ],
                    'partners_eyebrow' => 'Trusted Partners',
                    'partners_title' => 'Who We Work With',
                    'partners' => ['UNICEF India', 'GIZ India', 'Tata Trusts', 'CSR India', 'NABARD', 'Govt. of Maharashtra'],
                ],
                'media' => [
                    'hero_background' => [
                        'label' => 'Hero Background Image',
                        'path' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=1600&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Team collaborating in a community center',
                    ],
                ],
            ],
            'editor' => [
                'quick_fields' => [
                    'Hero' => [
                        ['key' => 'hero_title', 'label' => 'Hero Title', 'type' => 'text'],
                        ['key' => 'hero_subtitle', 'label' => 'Hero Subtitle', 'type' => 'textarea'],
                    ],
                    'Mission & Vision' => [
                        ['key' => 'mission_title', 'label' => 'Mission Title', 'type' => 'text'],
                        ['key' => 'mission_text', 'label' => 'Mission Text', 'type' => 'textarea'],
                        ['key' => 'vision_title', 'label' => 'Vision Title', 'type' => 'text'],
                        ['key' => 'vision_text', 'label' => 'Vision Text', 'type' => 'textarea'],
                    ],
                    'Advanced JSON' => [
                        ['key' => 'values', 'label' => 'Core Values (JSON)', 'type' => 'json'],
                        ['key' => 'milestones', 'label' => 'Journey Milestones (JSON)', 'type' => 'json'],
                        ['key' => 'team', 'label' => 'Team Members (JSON)', 'type' => 'json'],
                        ['key' => 'partners', 'label' => 'Partners (JSON)', 'type' => 'json'],
                    ],
                ],
                'media_keys' => ['hero_background'],
            ],
        ],

        'programs' => [
            'name' => 'Programs',
            'view' => 'pages.programs',
            'defaults' => [
                'meta' => [
                    'meta_title' => 'Our Programs — Sahayog Foundation',
                    'meta_description' => "Explore Sahayog Foundation's integrated programs in education, healthcare, livelihoods, environment, and women empowerment across rural India.",
                    'meta_keywords' => 'ngo programs, education, healthcare, livelihood, women empowerment, india',
                    'og_title' => 'Our Programs — Sahayog Foundation',
                    'og_description' => 'From classrooms to health camps, discover how Sahayog Foundation creates lasting impact across communities.',
                    'og_image' => 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=1200',
                ],
                'content' => [
                    'hero_title' => 'Our Programs',
                    'hero_subtitle' => 'Integrated initiatives that address the roots of poverty.',
                    'subnav' => [
                        ['id' => 'education', 'label' => 'Education'],
                        ['id' => 'health', 'label' => 'Healthcare'],
                        ['id' => 'livelihood', 'label' => 'Livelihoods'],
                        ['id' => 'environment', 'label' => 'Environment'],
                        ['id' => 'women', 'label' => 'Women'],
                        ['id' => 'digital', 'label' => 'Digital'],
                    ],
                    'sections' => [
                        [
                            'id' => 'education',
                            'eyebrow' => 'Program 01',
                            'title' => 'Education for All',
                            'body_1' => 'We believe education is the single most powerful lever for lasting change. Our Education for All program ensures that no child drops out of school due to poverty, lack of resources, or distance from learning centers.',
                            'body_2' => 'We run scholarship programs, bridge learning centers, digital classrooms, and parent sensitization workshops to keep children — especially girls — in school and learning.',
                            'highlights' => [
                                '₹3,500 scholarships for 2,000+ students annually',
                                '50+ community learning centers across 5 districts',
                                'Digital literacy for 8,000+ students',
                                '85% scholarship retention rate',
                            ],
                            'cta' => 'Support Education',
                        ],
                        [
                            'id' => 'health',
                            'eyebrow' => 'Program 02',
                            'title' => 'Community Healthcare',
                            'body_1' => 'Healthcare should not be a privilege. Our mobile health units bring qualified doctors, diagnostic equipment, and medicines directly to villages where the nearest hospital may be 50 km away.',
                            'body_2' => 'We focus on maternal health, child nutrition, preventive care, and early detection of diseases that are treatable when caught early but devastating when ignored.',
                            'highlights' => [
                                '12 mobile health vans serving 180+ villages',
                                '1,200+ health camps conducted annually',
                                'Free medicines distributed to 8,500+ patients',
                                'Maternal mortality reduced by 40% in target areas',
                            ],
                            'cta' => 'Support Healthcare',
                        ],
                        [
                            'id' => 'livelihood',
                            'eyebrow' => 'Program 03',
                            'title' => 'Sustainable Livelihoods',
                            'body_1' => 'Economic independence is the foundation of all other freedoms. We work with families to identify livelihood opportunities, build skills, link with markets, and access credit — enabling sustainable income growth.',
                            'body_2' => '',
                            'highlights' => [
                                'Skill training in 25+ trades and vocations',
                                '300+ self-help groups formed and active',
                                'Microfinance linkages for 3,200+ families',
                                'Average income increased by 65% post-program',
                            ],
                            'cta' => 'Support Livelihoods',
                        ],
                        [
                            'id' => 'environment',
                            'eyebrow' => 'Program 04',
                            'title' => 'Environment & Climate',
                            'body_1' => 'Climate change hits the poorest communities hardest. We work on watershed management, organic farming, tree plantation, and clean energy adoption to build climate-resilient communities.',
                            'body_2' => '',
                            'highlights' => [
                                '50,000+ trees planted across Maharashtra',
                                'Watershed projects restoring 1,200 acres',
                                '800+ solar lamp installations in tribal hamlets',
                                'Organic certification for 500+ farmers',
                            ],
                            'cta' => 'Support Environment',
                        ],
                        [
                            'id' => 'women',
                            'eyebrow' => 'Program 05',
                            'title' => 'Women Empowerment',
                            'body_1' => "When women lead, communities thrive. We invest in women's leadership, legal literacy, safety, and entrepreneurship — helping them claim their rights and transform their families and communities.",
                            'body_2' => '',
                            'highlights' => [
                                'Leadership training for 5,800+ women',
                                'Legal aid and rights awareness in 90+ villages',
                                '150+ women-led enterprises supported',
                                'Domestic violence intervention programs',
                            ],
                            'cta' => 'Support Women',
                        ],
                        [
                            'id' => 'digital',
                            'eyebrow' => 'Program 06',
                            'title' => 'Digital Inclusion',
                            'body_1' => 'The digital divide is widening inequality. We build community digital centers, train youth in digital skills, and connect communities to government services, markets, and learning resources online.',
                            'body_2' => '',
                            'highlights' => [
                                '200+ digital community centers established',
                                '15,000+ youth trained in digital skills',
                                'e-Governance access for 30,000+ households',
                                'Online market linkages for 800+ artisans',
                            ],
                            'cta' => 'Support Digital India',
                        ],
                    ],
                    'inner_cta_title' => 'Want to Partner With Us?',
                    'inner_cta_text' => 'We welcome CSR partnerships, institutional grants, and individual donors who share our vision.',
                    'inner_cta_primary' => 'Donate',
                    'inner_cta_secondary' => 'Get in Touch',
                ],
                'media' => [
                    'hero_background' => [
                        'label' => 'Hero Background Image',
                        'path' => 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=1600&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Volunteers helping children in classroom',
                    ],
                    'education_image' => [
                        'label' => 'Education Program Image',
                        'path' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=700&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Children studying in a bright classroom supported by Sahayog Foundation',
                    ],
                    'health_image' => [
                        'label' => 'Healthcare Program Image',
                        'path' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=700&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Doctor conducting mobile health camp in rural village',
                    ],
                    'livelihood_image' => [
                        'label' => 'Livelihood Program Image',
                        'path' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=700&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Women working in a tailoring unit supported by Sahayog Foundation',
                    ],
                    'environment_image' => [
                        'label' => 'Environment Program Image',
                        'path' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=700&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Community members planting trees as part of environmental restoration',
                    ],
                    'women_image' => [
                        'label' => 'Women Empowerment Program Image',
                        'path' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=700&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Group of empowered women from a rural self-help group',
                    ],
                    'digital_image' => [
                        'label' => 'Digital Inclusion Program Image',
                        'path' => 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=700&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Young people learning digital skills at a community center',
                    ],
                ],
            ],
            'editor' => [
                'quick_fields' => [
                    'Hero' => [
                        ['key' => 'hero_title', 'label' => 'Hero Title', 'type' => 'text'],
                        ['key' => 'hero_subtitle', 'label' => 'Hero Subtitle', 'type' => 'textarea'],
                    ],
                    'Inner CTA' => [
                        ['key' => 'inner_cta_title', 'label' => 'CTA Title', 'type' => 'text'],
                        ['key' => 'inner_cta_text', 'label' => 'CTA Text', 'type' => 'textarea'],
                        ['key' => 'inner_cta_primary', 'label' => 'CTA Primary Button', 'type' => 'text'],
                        ['key' => 'inner_cta_secondary', 'label' => 'CTA Secondary Button', 'type' => 'text'],
                    ],
                    'Advanced JSON' => [
                        ['key' => 'subnav', 'label' => 'Subnav (JSON)', 'type' => 'json'],
                        ['key' => 'sections', 'label' => 'Program Sections (JSON)', 'type' => 'json'],
                    ],
                ],
                'media_keys' => ['hero_background', 'education_image', 'health_image', 'livelihood_image', 'environment_image', 'women_image', 'digital_image'],
            ],
        ],

        'donate' => [
            'name' => 'Donate',
            'view' => 'pages.donate',
            'defaults' => [
                'meta' => [
                    'meta_title' => 'Donate — Sahayog Foundation',
                    'meta_description' => "Support Sahayog Foundation's life-changing work. Your donation funds education, healthcare, and sustainable livelihoods for communities in need.",
                    'meta_keywords' => 'donate ngo, support education india, donate healthcare, charity india',
                    'og_title' => 'Donate to Sahayog Foundation',
                    'og_description' => "Every rupee makes a difference. Support education, health, and opportunity for India's most underserved communities.",
                    'og_image' => 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=1200',
                ],
                'content' => [
                    'hero_title' => 'Make a Difference Today',
                    'hero_subtitle' => 'Donations are eligible for 80G tax deduction under the Income Tax Act.',
                    'impact_title' => 'Your Gift, Their Future',
                    'impact_cards' => [
                        ['amount' => '₹500', 'desc' => 'Provides school supplies and books for one child for an entire year'],
                        ['amount' => '₹1,000', 'desc' => 'Covers one month of nutrition supplements for 5 malnourished children'],
                        ['amount' => '₹2,500', 'desc' => 'Funds a complete medical check-up for 10 people in a mobile health camp'],
                        ['amount' => '₹5,000', 'desc' => 'Sponsors digital literacy training for one rural youth for 3 months'],
                    ],
                    'trust_badges' => [
                        'Registered NGO (Trust Reg. No. MH-2010-1234)',
                        '80G Tax Exemption Available',
                        '100% Secure Transactions',
                        'FCRA Approved for International Donors',
                    ],
                    'form_heading' => 'Choose Your Contribution',
                    'faq_eyebrow' => 'Questions',
                    'faq_title' => 'Frequently Asked',
                    'faqs' => [
                        [
                            'q' => 'Is my donation tax-deductible?',
                            'a' => 'Yes. Sahayog Foundation is registered under Section 12A and 80G of the Income Tax Act. All donations are eligible for 50% tax deduction. We will issue an 80G receipt within 48 hours.',
                        ],
                        [
                            'q' => 'Can I donate from outside India?',
                            'a' => 'Yes! We are FCRA approved and can accept international donations from individuals and organizations. Please contact us for FCRA bank details.',
                        ],
                        [
                            'q' => 'How is my donation used?',
                            'a' => 'At least 85% of all donations go directly to program expenses. We publish audited annual reports on our website. You can also opt to designate your donation to a specific program.',
                        ],
                        [
                            'q' => 'Can I set up a recurring donation?',
                            'a' => 'Yes. Monthly and annual recurring options are available. You can cancel or modify anytime by contacting us at info@sahayogfoundation.org.',
                        ],
                        [
                            'q' => 'Will I receive updates about my impact?',
                            'a' => 'Absolutely. All donors receive quarterly impact newsletters and annual reports. Major donors (₹25,000+) receive a personalized impact report.',
                        ],
                    ],
                ],
                'media' => [
                    'hero_background' => [
                        'label' => 'Hero Background Image',
                        'path' => 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=1600&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Donation concept image',
                    ],
                ],
            ],
            'editor' => [
                'quick_fields' => [
                    'Hero' => [
                        ['key' => 'hero_title', 'label' => 'Hero Title', 'type' => 'text'],
                        ['key' => 'hero_subtitle', 'label' => 'Hero Subtitle', 'type' => 'textarea'],
                        ['key' => 'impact_title', 'label' => 'Impact Section Title', 'type' => 'text'],
                    ],
                    'Advanced JSON' => [
                        ['key' => 'impact_cards', 'label' => 'Impact Cards (JSON)', 'type' => 'json'],
                        ['key' => 'trust_badges', 'label' => 'Trust Badges (JSON)', 'type' => 'json'],
                        ['key' => 'faqs', 'label' => 'FAQs (JSON)', 'type' => 'json'],
                    ],
                ],
                'media_keys' => ['hero_background'],
            ],
        ],

        'contact' => [
            'name' => 'Contact',
            'view' => 'pages.contact',
            'defaults' => [
                'meta' => [
                    'meta_title' => 'Contact Us — Sahayog Foundation',
                    'meta_description' => 'Get in touch with Sahayog Foundation. Reach out for volunteering, donations, partnerships, or general inquiries.',
                    'meta_keywords' => 'contact ngo, volunteer, csr partnership, sahayog foundation contact',
                    'og_title' => 'Contact Sahayog Foundation',
                    'og_description' => "We'd love to hear from you. Reach out to volunteer, partner, or support our mission.",
                    'og_image' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200',
                ],
                'content' => [
                    'hero_title' => "Let's Connect",
                    'hero_subtitle' => "We'd love to hear from you — whether you want to volunteer, partner, or simply say hello.",
                    'info_title' => 'Get in Touch',
                    'info_subtitle' => 'Our team typically responds within 1–2 business days.',
                    'address' => "42, Gandhi Road, Shivajinagar\nPune, Maharashtra 411001\nIndia",
                    'emails' => ['info@sahayogfoundation.org', 'programs@sahayogfoundation.org'],
                    'phone' => '+91 20 1234 5678',
                    'phone_note' => 'Mon – Sat, 9am – 6pm IST',
                    'hours' => "Monday – Saturday\n9:00 AM – 6:00 PM IST",
                    'social_label' => 'Follow Our Work',
                    'form_heading' => 'Send Us a Message',
                    'form_success_text' => "Thank you! We've received your message and will be in touch soon.",
                    'form_disclaimer' => 'We respect your privacy. Your information will never be shared with third parties.',
                    'map_title' => 'Find Us',
                    'map_subtitle' => '42, Gandhi Road, Shivajinagar, Pune – 411001, Maharashtra',
                ],
                'media' => [
                    'hero_background' => [
                        'label' => 'Hero Background Image',
                        'path' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1600&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'People collaborating in an office',
                    ],
                ],
            ],
            'editor' => [
                'quick_fields' => [
                    'Hero' => [
                        ['key' => 'hero_title', 'label' => 'Hero Title', 'type' => 'text'],
                        ['key' => 'hero_subtitle', 'label' => 'Hero Subtitle', 'type' => 'textarea'],
                    ],
                    'Contact Details' => [
                        ['key' => 'info_title', 'label' => 'Info Section Title', 'type' => 'text'],
                        ['key' => 'info_subtitle', 'label' => 'Info Section Subtitle', 'type' => 'textarea'],
                        ['key' => 'address', 'label' => 'Address', 'type' => 'textarea'],
                        ['key' => 'phone', 'label' => 'Primary Phone', 'type' => 'text'],
                        ['key' => 'phone_note', 'label' => 'Phone Note', 'type' => 'text'],
                        ['key' => 'hours', 'label' => 'Office Hours', 'type' => 'textarea'],
                    ],
                    'Advanced JSON' => [
                        ['key' => 'emails', 'label' => 'Emails (JSON)', 'type' => 'json'],
                    ],
                ],
                'media_keys' => ['hero_background'],
            ],
        ],

        'gallery' => [
            'name' => 'Gallery',
            'view' => 'gallery',
            'defaults' => [
                'meta' => [
                    'meta_title' => 'Our Gallery — Sahayog Foundation',
                    'meta_description' => 'Explore moments from Sahayog Foundation field programs across education, healthcare, livelihoods, and community impact.',
                    'meta_keywords' => 'ngo gallery, community impact photos, sahayog foundation images',
                    'og_title' => 'Our Gallery — Sahayog Foundation',
                    'og_description' => 'Stories in pictures from our work with communities across India.',
                    'og_image' => 'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=1200',
                ],
                'content' => [
                    'hero_title' => 'Our Gallery',
                    'hero_subtitle' => 'Stories of hope, dignity, and community-led change.',
                    'show_filters' => true,
                    'filter_all_label' => 'All',
                ],
                'media' => [
                    'hero_background' => [
                        'label' => 'Hero Background Image',
                        'path' => 'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=1600&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Children smiling during community event',
                    ],
                ],
                'gallery_items' => [
                    [
                        'key' => 'gallery_1',
                        'path' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Children in classroom supported by Sahayog',
                        'caption' => 'Learning center session in Solapur',
                        'category' => 'Education',
                        'sort_order' => 1,
                    ],
                    [
                        'key' => 'gallery_2',
                        'path' => 'https://images.unsplash.com/photo-1571210862729-78a52d3779a2?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Community health camp consultation',
                        'caption' => 'Mobile health camp outreach',
                        'category' => 'Healthcare',
                        'sort_order' => 2,
                    ],
                    [
                        'key' => 'gallery_3',
                        'path' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Women in livelihood training session',
                        'caption' => 'Women-led tailoring enterprise',
                        'category' => 'Livelihoods',
                        'sort_order' => 3,
                    ],
                    [
                        'key' => 'gallery_4',
                        'path' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Women empowerment workshop participants',
                        'caption' => 'Leadership workshop for women',
                        'category' => 'Women',
                        'sort_order' => 4,
                    ],
                    [
                        'key' => 'gallery_5',
                        'path' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Tree plantation drive by volunteers',
                        'caption' => 'Community-led tree plantation drive',
                        'category' => 'Environment',
                        'sort_order' => 5,
                    ],
                    [
                        'key' => 'gallery_6',
                        'path' => 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Digital literacy workshop with youth',
                        'caption' => 'Digital skills training center',
                        'category' => 'Digital',
                        'sort_order' => 6,
                    ],
                    [
                        'key' => 'gallery_7',
                        'path' => 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Volunteer teaching group of students',
                        'caption' => 'Volunteer classroom mentoring',
                        'category' => 'Education',
                        'sort_order' => 7,
                    ],
                    [
                        'key' => 'gallery_8',
                        'path' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1000&auto=format&fit=crop&q=80',
                        'is_external' => true,
                        'alt_text' => 'Doctor checkup at outreach camp',
                        'caption' => 'Village diagnostics day',
                        'category' => 'Healthcare',
                        'sort_order' => 8,
                    ],
                ],
            ],
            'editor' => [
                'quick_fields' => [
                    'Hero' => [
                        ['key' => 'hero_title', 'label' => 'Hero Title', 'type' => 'text'],
                        ['key' => 'hero_subtitle', 'label' => 'Hero Subtitle', 'type' => 'textarea'],
                    ],
                ],
                'media_keys' => ['hero_background'],
                'uses_gallery_manager' => true,
            ],
        ],
    ],

    'admin' => [
        'default_redirect' => '/admin',
    ],
];
